name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
     
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
     
      - name: Build test image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: rentcast-proxy:test
          cache-from: |
            type=gha,scope=integration-test
          cache-to: type=gha,scope=integration-test,mode=max
          platforms: linux/amd64
     
      - name: Run integration tests
        run: |
          # Start the application container
          docker run -d \
            --name rentcast-proxy-test \
            -p 3000:3000 \
            -e RENTCAST_API_KEY=test_key \
            rentcast-proxy:test
         
          # Wait for application to start
          echo "Waiting for application to start..."
          sleep 10
         
          # Check if application is healthy
          echo "Testing health endpoint..."
          curl -f http://localhost:3000/health || exit 1
         
          # Test CORS headers
          echo "Testing CORS headers..."
          response=$(curl -s -I http://localhost:3000/health)
          echo "$response" | grep -q "Access-Control-Allow-Origin: \*" || exit 1
         
          # Test 404 handling
          echo "Testing 404 handling..."
          status_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000/nonexistent)
          [ "$status_code" = "404" ] || exit 1
         
          echo "All integration tests passed!"
       
      - name: Cleanup
        if: always()
        run: |
          docker stop rentcast-proxy-test || true
          docker rm rentcast-proxy-test || true
